spring.application.name=cms-backend

spring.data.mongodb.uri=mongodb://localhost:27017/cmsDB_dev


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sevangalion@gmail.com
spring.mail.password=hnsusohrmnznzopj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

jwt.secret=ZGV2LWNtcy1iYWNrZW5kLWp3dC1zZWNyZXQta2V5LTEyMy00NTY3ODkw
jwt.expiration=14400000
file.upload-dir=uploads
logging.level.org.springframework.security=DEBUG
